const labels : string[] = [
    'Right:StopR',
    'Left:StopL',
    'Right:Peg3',
    'Right:Peg4',
    'Right:Kh3',
    'Right:Peg1',
    'Right:HKnuckle',
    'Right:HKnuckle2',
    'Right:HFladHori',
    'Right:HFladHori2',
    'Right:MediRightOk',
    'Left:MediLeftKnuckle',
    'Left:PegDu',
    'Right:Give1Right',
    'Left:Give1Left',
    'Right:Give2Right',
    'Left:Give2Left',
    'Right:Kan1',
    'Right:Kan2',
    'Right:Skal1',
    'Right:Skal2',
    'Left:Tage1',
    'Left:Tage2',
    'Right:Apotek1',
    'Right:Apotek2',
    'Right:Apotek3',
    'Left:Tak1',
    'Left:Tak2',
    'Left:Tak3',
    'Right:Help1Right',
    'Left:Help1Left',
    'Right:Help2Right',
    'Left:Help2Left'
]

export default labels;